### ISSUE TITLE
NPE on issue creation

### ISSUE THREAD

**Issue by cdupuis** [atomist/rug-functions-github#10]
```03/27 10:16:42.239 DEBUG [] c.a.k.MessagePoller - MSG_command_handler_request.request {payload={"rug":{"group":"atomist-rugs","artifact":"github-handlers","name":"CreateGithubIssue","version":"0.18.7","type":"command_handler"},"team":{"id":"T095SFFBK","name":"atomist","owner":"atomisthq","secret_path":"secret/teams/atomisthq/github"},"correlation_context":{"team":{"id":"T095SFFBK"},"channel":{"id":"C095SFFC1"},"user":{"id":"U4PJPPZ0S"},"thread_ts":"1490607803.272777"},"corrid":"b4e3831d-37c7-4eb3-80fa-9680e6a4aee4::atomist::general::T095SFFBK::C095SFFC1","secrets":[{"name":"github://user_token?scopes=repo","value":"secret/users/WillGardella/github"}],"parameters":[{"name":"title","value":"Abuse detection mechanism encountered"},{"name":"body","value":"Everyone at the offsite was trying to create new rug projects at the same time, and I encountered a rate limiting problem."}],"mapped_parameters":[{"name":"repo","value":"product-development"},{"name":"owner","value":"atomisthq"},{"name":"corrid","value":"b4e3831d-37c7-4eb3-80fa-9680e6a4aee4::atomist::general::T095SFFBK::C095SFFC1"}]}}
03/27 10:16:42.239 INFO  [l:b8ccec8d-2437-4e6d-9e5a-772e81615b] c.a.r.r.i.OperationCoordinator - Loading operation invoker for atomist-rugs:github-handlers:0.18.7:T095SFFBK
03/27 10:16:42.330 INFO  [l:b8ccec8d-2437-4e6d-9e5a-772e81615b] c.a.r.r.i.OperationCoordinator - Obtained repo configuration for team T095SFFBK: url 'https://atomist.jfrog.io/atomist/T095SFFBK'
03/27 10:16:42.331 INFO  [l:b8ccec8d-2437-4e6d-9e5a-772e81615b] c.a.r.r.i.OperationCoordinator - Loaded operation invoker for atomist-rugs:github-handlers:0.18.7:T095SFFBK
03/27 10:16:42.336 INFO  [l:b8ccec8d-2437-4e6d-9e5a-772e81615b] c.a.r.r.i.o.CommandHandlerInvoker - Invoking command-handler-CreateGithubIssue of atomist-rugs:github-handlers:0.18.7
03/27 10:16:42.375 INFO  [l:b8ccec8d-2437-4e6d-9e5a-772e81615b] c.a.r.r.l.CachingRugLoader - Returning cached Rug operations for atomist-rugs:github-handlers:0.18.7
03/27 10:16:42.375 INFO  [l:b8ccec8d-2437-4e6d-9e5a-772e81615b] c.a.r.r.i.o.CommandHandlerInvoker - Loaded command-handler-CreateGithubIssue of atomist-rugs:github-handlers:0.18.7
03/27 10:16:42.962 WARN  [] c.a.r.f.g.CreateIssueFunction - Failed to create issue in `atomisthq/product-development`
java.lang.NullPointerException: null
	at com.atomist.rug.function.github.CreateIssueFunction$$anonfun$1.apply(CreateIssueFunction.scala:33)
	at com.atomist.rug.function.github.CreateIssueFunction$$anonfun$1.apply(CreateIssueFunction.scala:30)
	at scala.util.Try$.apply(Try.scala:192)
	at com.atomist.rug.function.github.CreateIssueFunction.invoke(CreateIssueFunction.scala:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.atomist.rug.spi.AnnotatedRugFunction$class.run(AnnotatedRugFunction.scala:61)
	at com.atomist.rug.function.github.CreateIssueFunction.run(CreateIssueFunction.scala:15)
	at com.atomist.rug.runtime.plans.LocalInstructionRunner.run(LocalInstructionRunner.scala:45)```

**Comment by alankstewart** [comment]
Code has changed considerably since 27th March and an NPE would no longer be thrown.
