### ISSUE TITLE
listing issues is not working

### ISSUE THREAD

**Issue by ddgenome** [atomist/rug-functions-github#24]
A bit surprising. I guess this needs a test.

```
08/30 17:47:48.712 [command-handler-pool-7] INFO  [56eb990f-9811-4022-9966-cc255ba555bd] c.a.r.r.i.o.HandlerRugFunctionRegistry - Loaded rug function list-github-user-issues from file:/root/.atomist/repository/com/atomist/rug/rug-functions-github/0.22.0/rug-functions-github-0.22.0.jar
08/30 17:47:53.781 [command-handler-pool-7] WARN  [56eb990f-9811-4022-9966-cc255ba555bd] c.a.r.f.g.i.ListUserIssuesFunction - Failed to list issues
java.lang.ClassCastException: com.atomist.source.git.domain.IssueRepository cannot be cast to com.atomist.source.git.domain.Repository
    at com.atomist.rug.function.github.issue.ListUserIssuesFunction$$anonfun$4.apply(ListUserIssuesFunction.scala:61)
    at com.atomist.rug.function.github.issue.ListUserIssuesFunction$$anonfun$4.apply(ListUserIssuesFunction.scala:50)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at com.atomist.rug.function.github.issue.ListUserIssuesFunction.invoke(ListUserIssuesFunction.scala:50)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.atomist.rug.spi.AnnotatedRugFunction$class.run(AnnotatedRugFunction.scala:66)
    at com.atomist.rug.function.github.issue.ListUserIssuesFunction.run(ListUserIssuesFunction.scala:16)
    at com.atomist.rug.runtime.plans.LocalInstructionRunner$$anonfun$2.apply(LocalInstructionRunner.scala:51)
    at com.atomist.rug.runtime.plans.LocalInstructionRunner$$anonfun$2.apply(LocalInstructionRunner.scala:51)
    at scala.util.Try$.apply(Try.scala:192)
    at com.atomist.rug.runtime.plans.LocalInstructionRunner.run(LocalInstructionRunner.scala:50)
    at com.atomist.rug.runtime.plans.LocalPlanRunner$$anonfun$7.apply(LocalPlanRunner.scala:51)
    at com.atomist.rug.runtime.plans.LocalPlanRunner$$anonfun$7.apply(LocalPlanRunner.scala:51)
    at scala.util.Try$.apply(Try.scala:192)
    at com.atomist.rug.runtime.plans.LocalPlanRunner.com$atomist$rug$runtime$plans$LocalPlanRunner$$handleInstruction(LocalPlanRunner.scala:50)
    at com.atomist.rug.runtime.plans.LocalPlanRunner$$anonfun$5.apply(LocalPlanRunner.scala:43)
    at com.atomist.rug.runtime.plans.LocalPlanRunner$$anonfun$5.apply(LocalPlanRunner.scala:42)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.immutable.List.map(List.scala:285)
    at com.atomist.rug.runtime.plans.LocalPlanRunner.run(LocalPlanRunner.scala:42)
    at com.atomist.rug.runner.invoke.operation.CommandHandlerInvoker.invokeCommandHandler(CommandHandlerInvoker.java:93)
    at com.atomist.rug.runner.invoke.ClasspathScopedRugInvoker.invokeCommandHandler(ClasspathScopedRugInvoker.java:66)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.atomist.rug.runner.invoke.RugInvoker.handleCommandHandler(RugInvoker.java:167)
    at com.atomist.rug.runner.service.CommandHandlerDispatcher$$anonfun$1.apply$mcV$sp(CommandHandlerDispatcher.scala:69)
    at com.atomist.rug.runner.service.CommandHandlerDispatcher$$anonfun$1.apply(CommandHandlerDispatcher.scala:63)
    at com.atomist.rug.runner.service.CommandHandlerDispatcher$$anonfun$1.apply(CommandHandlerDispatcher.scala:63)
    at scala.util.Try$.apply(Try.scala:192)
    at com.atomist.rug.runner.service.CommandHandlerDispatcher.invoke(CommandHandlerDispatcher.scala:63)
    at com.atomist.rug.runner.service.CommandHandlerDispatcher$$anonfun$poll$1$$anonfun$apply$mcV$sp$1.apply(CommandHandlerDispatcher.scala:40)
    at com.atomist.rug.runner.service.CommandHandlerDispatcher$$anonfun$poll$1$$anonfun$apply$mcV$sp$1.apply(CommandHandlerDispatcher.scala:40)
    at com.atomist.kafka.MessagePoller$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply$mcV$sp(MessagePoller.scala:77)
    at com.atomist.kafka.MessagePoller$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply(MessagePoller.scala:77)
```

**Comment by ddgenome** [comment]
This appears to be due to a different versions of artifact-source being loaded by rug-runner compared to that rug-functions-github is being compiled against.

**Comment by ddgenome** [comment]
rug-functions-github has a newer one. So I will probably have to revert to an older version of rug-functions-github in github-rugs, which may break other things.

**Comment by ddgenome** [comment]
Except that everything seems to be using artifact-source-1.0.0-m.19.

**Comment by ddgenome** [comment]
And everything works locally

**Comment by ddgenome** [comment]
Internal systems may be picking up the wrong version of artifact-source. Closing this.
